# .github/workflows/main.yml
name: Deploy main via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server via SSH
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_USER: ${{ vars.SSH_USER }}
          SSH_HOST: ${{ vars.SSH_HOST }}
          SSH_PORT: ${{ vars.SSH_PORT }}
        run: |
          ssh -o StrictHostKeyChecking=no \
              -i <(echo "$SSH_KEY") \
              -p "$SSH_PORT" \
              "$SSH_USER@$SSH_HOST" \
              "chmod +x ~/elysia/deploy.sh && bash ~/elysia/deploy.sh"
